import { EnrichedRepo, Category } from '@/types/repo';

/**
 * Hardcoded list of exactly 58 content categories across 6 lifecycle groups.
 * These are fixed buckets — never derived dynamically from tags.
 * A repo can belong to multiple categories (allCategories).
 * primaryCategory = category with the most matching tags.
 */
export const CATEGORIES: Category[] = [

  // ─── Group 1: Foundation & Training ────────────────────────────────────────

  {
    id: 'transformer-architecture',
    name: 'Transformer Architecture',
    icon: '🔬',
    color: '#6366f1',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Transformer model design, attention mechanisms, and architectural innovations',
    tags: ['transformer', 'attention', 'llm', 'gpt', 'llama', 'mistral', 'phi', 'mixtral', 'gemini', 'claude', 'openai', 'anthropic'],
  },
  {
    id: 'attention-mechanisms',
    name: 'Attention Mechanisms',
    icon: '🧠',
    color: '#7c3aed',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Self-attention, cross-attention, flash attention, and memory-efficient variants',
    tags: ['attention', 'transformer', 'llm'],
  },
  {
    id: 'pretraining-scaling',
    name: 'Pre-training & Scaling',
    icon: '⚗️',
    color: '#8b5cf6',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Large-scale pre-training, scaling laws, and distributed training infrastructure',
    tags: ['llm', 'transformer', 'dataset', 'synthetic-data'],
  },
  {
    id: 'fine-tuning-methods',
    name: 'Fine-tuning Methods',
    icon: '🎯',
    color: '#a78bfa',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Supervised fine-tuning, instruction tuning, LoRA, QLoRA, and PEFT techniques',
    tags: ['fine-tuning', 'lora', 'qlora', 'peft', 'llm'],
  },
  {
    id: 'rlhf-alignment',
    name: 'RLHF & Alignment',
    icon: '🎖️',
    color: '#c4b5fd',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Reinforcement learning from human feedback, alignment, and reward modeling',
    tags: ['rlhf', 'dpo', 'fine-tuning', 'llm'],
  },
  {
    id: 'dpo-preference-learning',
    name: 'DPO & Preference Learning',
    icon: '⚖️',
    color: '#818cf8',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Direct preference optimization, ORPO, and preference dataset construction',
    tags: ['dpo', 'rlhf', 'fine-tuning'],
  },
  {
    id: 'dataset-curation',
    name: 'Dataset Curation',
    icon: '🗂️',
    color: '#6366f1',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Training data collection, filtering, deduplication, and quality assessment',
    tags: ['dataset', 'data-augmentation', 'synthetic-data'],
  },
  {
    id: 'data-pipelines',
    name: 'Data Pipelines',
    icon: '🔄',
    color: '#4f46e5',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'ETL pipelines, data versioning, and preprocessing at scale',
    tags: ['dataset', 'dvc', 'mlops'],
  },
  {
    id: 'synthetic-dataset-generation',
    name: 'Synthetic Dataset Generation',
    icon: '🧪',
    color: '#4338ca',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Generating synthetic training data, distillation datasets, and augmentation pipelines',
    tags: ['synthetic-data', 'dataset', 'data-augmentation', 'llm'],
  },
  {
    id: 'data-augmentation',
    name: 'Data Augmentation',
    icon: '➕',
    color: '#3730a3',
    repoCount: 0,
    lifecycleGroup: 'Foundation & Training',
    description: 'Techniques for expanding and diversifying training datasets',
    tags: ['data-augmentation', 'synthetic-data', 'dataset'],
  },

  // ─── Group 2: Inference & Deployment ───────────────────────────────────────

  {
    id: 'inference-engines',
    name: 'Inference Engines',
    icon: '🚀',
    color: '#f97316',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'High-performance inference runtimes, batching, and throughput optimization',
    tags: ['inference', 'vllm', 'tgi', 'tensorrt', 'onnx', 'llm'],
  },
  {
    id: 'serving-infrastructure',
    name: 'Serving Infrastructure',
    icon: '🖥️',
    color: '#ea580c',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'Model serving APIs, load balancing, and production deployment infrastructure',
    tags: ['inference', 'vllm', 'tgi', 'mlops'],
  },
  {
    id: 'kv-cache-optimization',
    name: 'KV Cache Optimization',
    icon: '💾',
    color: '#c2410c',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'Key-value cache management, prefix caching, and memory-efficient inference',
    tags: ['inference', 'vllm', 'llm'],
  },
  {
    id: 'quantization',
    name: 'Quantization',
    icon: '📉',
    color: '#fb923c',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'INT4/INT8/FP8 quantization, GPTQ, AWQ, and post-training quantization',
    tags: ['quantization', 'onnx', 'tensorrt', 'inference', 'llm'],
  },
  {
    id: 'model-pruning',
    name: 'Model Pruning',
    icon: '✂️',
    color: '#fed7aa',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'Structured and unstructured pruning to reduce model size and compute',
    tags: ['pruning', 'quantization', 'distillation'],
  },
  {
    id: 'knowledge-distillation',
    name: 'Knowledge Distillation',
    icon: '🧬',
    color: '#fdba74',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'Teacher-student training to compress large models into smaller, faster ones',
    tags: ['distillation', 'pruning', 'fine-tuning'],
  },
  {
    id: 'on-device-inference',
    name: 'On-Device Inference',
    icon: '📱',
    color: '#f97316',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'Running models locally on CPU/NPU, mobile, and embedded devices',
    tags: ['edge-ai', 'mobile-ml', 'onnx', 'tensorrt', 'inference'],
  },
  {
    id: 'mobile-edge-ml',
    name: 'Mobile & Edge ML',
    icon: '📡',
    color: '#ea580c',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'ML frameworks and toolchains optimized for mobile and edge hardware',
    tags: ['mobile-ml', 'edge-ai', 'onnx'],
  },
  {
    id: 'webgpu-wasm-inference',
    name: 'WebGPU / WASM Inference',
    icon: '🌐',
    color: '#c2410c',
    repoCount: 0,
    lifecycleGroup: 'Inference & Deployment',
    description: 'In-browser model inference using WebGPU, WebAssembly, and ONNX.js',
    tags: ['webgpu', 'onnx', 'edge-ai', 'inference'],
  },

  // ─── Group 3: LLM Application Layer ────────────────────────────────────────

  {
    id: 'agent-frameworks',
    name: 'Agent Frameworks',
    icon: '🤖',
    color: '#8b5cf6',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Frameworks for building autonomous LLM agents with planning and memory',
    tags: ['agent', 'langchain', 'langgraph', 'autogen', 'tool-use', 'llm'],
  },
  {
    id: 'multi-agent-systems',
    name: 'Multi-Agent Systems',
    icon: '🕸️',
    color: '#7c3aed',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Coordination, communication, and orchestration of multiple AI agents',
    tags: ['multi-agent', 'agent', 'autogen', 'langgraph'],
  },
  {
    id: 'rag-pipelines',
    name: 'RAG Pipelines',
    icon: '🔍',
    color: '#06b6d4',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Retrieval-augmented generation pipelines, indexing, and query orchestration',
    tags: ['rag-pipeline', 'rag', 'embeddings', 'vector-search', 'chunking', 'faiss', 'qdrant', 'weaviate', 'pinecone', 'chroma'],
  },
  {
    id: 'vector-databases',
    name: 'Vector Databases',
    icon: '🗄️',
    color: '#0891b2',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Scalable vector storage and approximate nearest-neighbor search systems',
    tags: ['faiss', 'qdrant', 'weaviate', 'pinecone', 'chroma', 'vector-search', 'embeddings'],
  },
  {
    id: 'chunking-embedding',
    name: 'Chunking & Embedding',
    icon: '🧩',
    color: '#0e7490',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Document chunking strategies, embedding models, and semantic indexing',
    tags: ['chunking', 'embeddings', 'rag-pipeline', 'vector-search'],
  },
  {
    id: 'memory-systems',
    name: 'Memory Systems',
    icon: '🧠',
    color: '#155e75',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Short-term and long-term memory architectures for AI agents',
    tags: ['agent', 'rag-pipeline', 'vector-search', 'embeddings'],
  },
  {
    id: 'function-calling',
    name: 'Function Calling',
    icon: '⚡',
    color: '#22d3ee',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Tool use via structured function calling, native and constrained decoding',
    tags: ['function-calling', 'tool-use', 'structured-output', 'json-schema', 'mcp'],
  },
  {
    id: 'mcp-servers-clients',
    name: 'MCP Servers & Clients',
    icon: '🔌',
    color: '#06b6d4',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Model Context Protocol servers and clients for tool integration',
    tags: ['mcp', 'function-calling', 'tool-use', 'agent'],
  },
  {
    id: 'browser-automation',
    name: 'Browser Automation',
    icon: '🌍',
    color: '#0284c7',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'LLM-driven browser control, web scraping, and UI automation agents',
    tags: ['agent', 'tool-use', 'function-calling'],
  },
  {
    id: 'json-structured-extraction',
    name: 'JSON / Structured Extraction',
    icon: '📋',
    color: '#0369a1',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Reliable structured output, constrained generation, and data extraction',
    tags: ['structured-output', 'json-schema', 'function-calling', 'prompt-engineering'],
  },
  {
    id: 'prompt-optimization',
    name: 'Prompt Optimization',
    icon: '✨',
    color: '#075985',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Automated prompt optimization, DSPy, and prompt search strategies',
    tags: ['prompt-engineering', 'chain-of-thought', 'llm'],
  },
  {
    id: 'chain-of-thought',
    name: 'Chain-of-Thought',
    icon: '💭',
    color: '#0c4a6e',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Reasoning chains, scratchpads, tree-of-thought, and multi-step inference',
    tags: ['chain-of-thought', 'prompt-engineering', 'agent', 'llm'],
  },
  {
    id: 'graph-databases',
    name: 'Graph Databases',
    icon: '🕸️',
    color: '#38bdf8',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Graph-based storage and traversal for knowledge-intensive AI applications',
    tags: ['knowledge-graph', 'graphrag', 'neo4j'],
  },
  {
    id: 'entity-extraction',
    name: 'Entity Extraction',
    icon: '🏷️',
    color: '#7dd3fc',
    repoCount: 0,
    lifecycleGroup: 'LLM Application Layer',
    description: 'Named entity recognition, relation extraction, and information extraction',
    tags: ['structured-output', 'nlp', 'json-schema'],
  },

  // ─── Group 4: Eval / Safety / Ops ──────────────────────────────────────────

  {
    id: 'eval-frameworks',
    name: 'Eval Frameworks',
    icon: '📊',
    color: '#ef4444',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Evaluation harnesses, test suites, and automated assessment pipelines',
    tags: ['evals', 'benchmarks', 'openai-evals', 'lm-evaluation-harness'],
  },
  {
    id: 'benchmarking',
    name: 'Benchmarking',
    icon: '🏁',
    color: '#dc2626',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Standardized benchmarks, leaderboards, and comparative model evaluation',
    tags: ['benchmarks', 'evals', 'lm-evaluation-harness'],
  },
  {
    id: 'llm-as-judge',
    name: 'LLM-as-Judge',
    icon: '⚖️',
    color: '#b91c1c',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Using LLMs to evaluate model outputs, pairwise preference, and scoring',
    tags: ['evals', 'benchmarks', 'llm'],
  },
  {
    id: 'content-moderation',
    name: 'Content Moderation',
    icon: '🛡️',
    color: '#991b1b',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Classifiers and systems for detecting harmful, offensive, or policy-violating content',
    tags: ['content-moderation', 'guardrails', 'red-teaming', 'jailbreak'],
  },
  {
    id: 'red-teaming',
    name: 'Red Teaming',
    icon: '🔴',
    color: '#7f1d1d',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Adversarial probing, jailbreak research, and model robustness testing',
    tags: ['red-teaming', 'jailbreak', 'guardrails', 'evals'],
  },
  {
    id: 'prompt-injection-defense',
    name: 'Prompt Injection Defense',
    icon: '🔒',
    color: '#450a0a',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Defenses against prompt injection, data exfiltration, and adversarial prompts',
    tags: ['guardrails', 'red-teaming', 'jailbreak', 'prompt-engineering'],
  },
  {
    id: 'llm-tracing-logging',
    name: 'LLM Tracing & Logging',
    icon: '👁️',
    color: '#10b981',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Distributed tracing, prompt logging, and observability for LLM applications',
    tags: ['wandb', 'mlflow', 'evals'],
  },
  {
    id: 'cost-latency-monitoring',
    name: 'Cost & Latency Monitoring',
    icon: '📈',
    color: '#059669',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Tracking inference costs, token usage, and latency across model deployments',
    tags: ['mlflow', 'wandb', 'mlops'],
  },
  {
    id: 'experiment-tracking',
    name: 'Experiment Tracking',
    icon: '🔭',
    color: '#047857',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'ML experiment management, hyperparameter logging, and reproducibility',
    tags: ['mlflow', 'wandb', 'dvc', 'mlops'],
  },
  {
    id: 'model-registry',
    name: 'Model Registry',
    icon: '📦',
    color: '#065f46',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Versioning, cataloging, and managing trained model artifacts',
    tags: ['mlflow', 'mlops', 'dvc'],
  },
  {
    id: 'ml-cicd',
    name: 'ML CI/CD',
    icon: '⚙️',
    color: '#064e3b',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Continuous integration and delivery pipelines for ML models and datasets',
    tags: ['mlops', 'dvc', 'mlflow'],
  },
  {
    id: 'bias-fairness',
    name: 'Bias & Fairness',
    icon: '🎭',
    color: '#6ee7b7',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Detecting and mitigating bias, evaluating demographic fairness in model outputs',
    tags: ['evals', 'benchmarks', 'guardrails'],
  },
  {
    id: 'model-cards-compliance',
    name: 'Model Cards & Compliance',
    icon: '📄',
    color: '#a7f3d0',
    repoCount: 0,
    lifecycleGroup: 'Eval / Safety / Ops',
    description: 'Model documentation, transparency reports, and regulatory compliance tooling',
    tags: ['evals', 'mlops', 'benchmarks'],
  },

  // ─── Group 5: Modality-Specific ─────────────────────────────────────────────

  {
    id: 'image-classification',
    name: 'Image Classification',
    icon: '🖼️',
    color: '#84cc16',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'CNN and ViT models for image recognition and classification tasks',
    tags: ['computer-vision', 'clip', 'yolo', 'detectron'],
  },
  {
    id: 'object-detection',
    name: 'Object Detection',
    icon: '🎯',
    color: '#65a30d',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Real-time and batch object detection, bounding box regression, and tracking',
    tags: ['yolo', 'detectron', 'computer-vision'],
  },
  {
    id: 'semantic-segmentation',
    name: 'Semantic Segmentation',
    icon: '🗺️',
    color: '#4d7c0f',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Pixel-level semantic and instance segmentation of images and videos',
    tags: ['sam', 'segment-anything', 'computer-vision', 'detectron'],
  },
  {
    id: 'vision-transformers',
    name: 'Vision Transformers',
    icon: '👁',
    color: '#3f6212',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'ViT, Swin, DeiT, and transformer-based architectures for vision tasks',
    tags: ['clip', 'computer-vision', 'transformer', 'multimodal'],
  },
  {
    id: 'speech-recognition-asr',
    name: 'Speech Recognition (ASR)',
    icon: '🎙️',
    color: '#a855f7',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Automatic speech recognition, transcription, and speaker diarization',
    tags: ['whisper', 'asr', 'speech'],
  },
  {
    id: 'text-to-speech-tts',
    name: 'Text-to-Speech (TTS)',
    icon: '🔊',
    color: '#9333ea',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Neural TTS, voice cloning, and expressive speech synthesis systems',
    tags: ['tts', 'speech', 'audio'],
  },
  {
    id: 'audio-generation',
    name: 'Audio Generation',
    icon: '🎵',
    color: '#7e22ce',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Music generation, sound design, and neural audio synthesis',
    tags: ['audio', 'speech', 'tts', 'asr'],
  },
  {
    id: 'diffusion-models',
    name: 'Diffusion Models',
    icon: '🌊',
    color: '#ec4899',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'DDPM, DDIM, flow matching, and score-based generative models',
    tags: ['diffusion', 'stable-diffusion', 'flux', 'comfyui', 'controlnet', 'image-generation'],
  },
  {
    id: 'image-generation',
    name: 'Image Generation',
    icon: '🎨',
    color: '#db2777',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Text-to-image, image-to-image, inpainting, and creative image synthesis',
    tags: ['image-generation', 'diffusion', 'stable-diffusion', 'flux', 'comfyui', 'controlnet'],
  },
  {
    id: 'video-generation',
    name: 'Video Generation',
    icon: '🎬',
    color: '#be185d',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Text-to-video, video editing, and temporal diffusion models',
    tags: ['video-generation', 'diffusion', 'image-generation'],
  },
  {
    id: 'text-classification',
    name: 'Text Classification',
    icon: '📝',
    color: '#3b82f6',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Sentiment analysis, topic classification, and document categorization',
    tags: ['nlp', 'transformer', 'llm'],
  },
  {
    id: 'named-entity-recognition',
    name: 'Named Entity Recognition',
    icon: '🏷️',
    color: '#2563eb',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Extracting entities (people, places, organizations) from unstructured text',
    tags: ['nlp', 'structured-output', 'transformer'],
  },
  {
    id: 'machine-translation',
    name: 'Machine Translation',
    icon: '🌐',
    color: '#1d4ed8',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Neural machine translation, multilingual models, and localization tooling',
    tags: ['nlp', 'transformer', 'llm'],
  },
  {
    id: 'vision-language-models',
    name: 'Vision-Language Models',
    icon: '🔭',
    color: '#1e40af',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Multimodal models combining vision and language, VQA, and image captioning',
    tags: ['vision-language', 'clip', 'multimodal', 'sam'],
  },
  {
    id: 'document-understanding',
    name: 'Document Understanding',
    icon: '📄',
    color: '#1e3a8a',
    repoCount: 0,
    lifecycleGroup: 'Modality-Specific',
    description: 'Layout-aware document AI, OCR, table extraction, and document QA',
    tags: ['nlp', 'vision-language', 'multimodal', 'structured-output'],
  },

  // ─── Group 6: Applied AI ─────────────────────────────────────────────────────

  {
    id: 'code-generation',
    name: 'Code Generation',
    icon: '💻',
    color: '#0ea5e9',
    repoCount: 0,
    lifecycleGroup: 'Applied AI',
    description: 'LLM-powered code synthesis, completion, and test generation',
    tags: ['code-generation', 'coding-assistant', 'llm'],
  },
  {
    id: 'code-review-analysis',
    name: 'Code Review & Analysis',
    icon: '🔎',
    color: '#0284c7',
    repoCount: 0,
    lifecycleGroup: 'Applied AI',
    description: 'Automated code review, static analysis, and vulnerability detection with LLMs',
    tags: ['code-generation', 'coding-assistant'],
  },
  {
    id: 'robot-learning',
    name: 'Robot Learning',
    icon: '🦾',
    color: '#f59e0b',
    repoCount: 0,
    lifecycleGroup: 'Applied AI',
    description: 'Imitation learning, policy learning, and reinforcement learning for robots',
    tags: ['robotics', 'ros', 'sim-to-real'],
  },
  {
    id: 'simulation-sim-to-real',
    name: 'Simulation & Sim-to-Real',
    icon: '🕹️',
    color: '#d97706',
    repoCount: 0,
    lifecycleGroup: 'Applied AI',
    description: 'Physics simulation, synthetic environments, and domain randomization',
    tags: ['sim-to-real', 'robotics', 'ros'],
  },
  {
    id: 'protein-structure-prediction',
    name: 'Protein Structure Prediction',
    icon: '🧬',
    color: '#22c55e',
    repoCount: 0,
    lifecycleGroup: 'Applied AI',
    description: 'AlphaFold and successor models for 3D protein structure prediction',
    tags: ['protein-folding', 'alphafold', 'drug-discovery'],
  },
  {
    id: 'drug-discovery',
    name: 'Drug Discovery',
    icon: '💊',
    color: '#16a34a',
    repoCount: 0,
    lifecycleGroup: 'Applied AI',
    description: 'Molecular generation, docking, and AI-driven drug candidate screening',
    tags: ['drug-discovery', 'protein-folding', 'alphafold'],
  },
  {
    id: 'collaborative-filtering',
    name: 'Collaborative Filtering',
    icon: '🎯',
    color: '#15803d',
    repoCount: 0,
    lifecycleGroup: 'Applied AI',
    description: 'User-item recommendation, matrix factorization, and neural recommendation models',
    tags: ['collaborative-filtering', 'recommendation'],
  },
];

/**
 * Determine the primary category for a repo based on its enriched tags.
 * Returns the category with the most tag matches. Returns '' if none match.
 */
function assignPrimaryCategory(repo: EnrichedRepo): string {
  let bestCategory = '';
  let bestCount = 0;
  for (const cat of CATEGORIES) {
    const count = repo.enrichedTags.filter(t => cat.tags.includes(t)).length;
    if (count > bestCount) {
      bestCount = count;
      bestCategory = cat.name;
    }
  }
  return bestCategory;
}

/**
 * Build category analytics and assign primaryCategory + allCategories to each repo.
 * Mutates each repo's primaryCategory and allCategories fields.
 * Always returns exactly the hardcoded CATEGORIES list (filtered to repoCount > 0).
 *
 * @param repos - All enriched repos
 * @returns Array of Category objects sorted by repoCount descending
 */
export function buildCategories(repos: EnrichedRepo[]): Category[] {
  // Assign primaryCategory and allCategories to each repo
  for (const repo of repos) {
    repo.primaryCategory = assignPrimaryCategory(repo);
    repo.allCategories = CATEGORIES
      .filter(cat => repo.enrichedTags.some(t => cat.tags.includes(t)))
      .map(cat => cat.name);
  }

  // Build repoCount for each category (count repos where category is in allCategories)
  return CATEGORIES
    .map(cat => ({
      ...cat,
      repoCount: repos.filter(r => r.allCategories.includes(cat.name)).length,
    }))
    .filter(c => c.repoCount > 0)
    .sort((a, b) => b.repoCount - a.repoCount);
}
