// KAN-172: Vercel Edge Middleware that returns a real HTTP 404 status for
// unknown / private /repo/[name]/ slugs.
//
// Background:
// - KAN-162 added `notFound()` in /repo/[name]/page.tsx and a project-level
//   not-found.tsx. The page body rendered correctly but Vercel's dynamic
//   prerender continued to serve unknown slugs with HTTP 200.
// - KAN-164 added a segment-level not-found.tsx. Same outcome: body correct,
//   status 200.
// - Root cause: with `dynamicParams: true` (the default for the Vercel target,
//   per ADR-005), Next.js generates a 200 fallback page on first hit for any
//   slug not in generateStaticParams. The route's body invokes notFound() and
//   renders the 404 UI, but Vercel's response status is bound at the prerender
//   layer, not the runtime render layer.
//
// Fix:
// - Edge Middleware runs BEFORE the route handler. We check the requested slug
//   against a build-time allowlist (data/repo-slugs.json, generated by
//   scripts/build-repo-slugs.cjs from public/data/library.json's
//   isPrivate=false repos).
// - Unknown / private slugs get NextResponse.rewrite(...) to the same path
//   with `status: 404`. The route still renders normally (notFound() inside
//   page.tsx → segment not-found.tsx body), but the wire status is now 404.
//
// Privacy guard: only repos with isPrivate === false are in the allowlist.
// Pairs with reporium-api#450 (centralized public_repo_filter) and
// reporium#278 (static-artifact validator). Three layers of defense:
//   1. API filters private repos at the wire (#450)
//   2. Static artifact validator fails the build if private leaks (#278)
//   3. Middleware returns 404 for any slug not in the public allowlist (this)
//
// Compatibility: this only runs on the Vercel target. The github-pages static
// export (REPORIUM_DEPLOY_TARGET=github-pages) does not deploy middleware
// (Next.js drops it from the export output). That target relies on
// generateStaticParams emitting all known public slugs, with everything else
// hitting GitHub Pages's default 404.

import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

// Build-time allowlist. Statically imported so Next.js inlines it into the
// Edge Runtime bundle (must stay well under the ~1 MB Edge bundle limit;
// current size ~26 KB for ~1867 slug strings).
import slugList from './data/repo-slugs.json';

const ALLOWLIST = new Set<string>(slugList as string[]);

export const config = {
  // Match every /repo/<slug>/... path. Excludes the bare /repo/ root and
  // static asset routes (the negative-lookahead ensures we don't intercept
  // _next or api).
  matcher: ['/repo/:slug/:path*', '/repo/:slug'],
};

export default function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Path is /repo/<slug>(/...)?(/)? — pull the first segment after /repo/.
  // Defensive parse: collapse repeated slashes, drop leading "/repo/".
  const match = pathname.match(/^\/repo\/([^/]+)/);
  if (!match) {
    return NextResponse.next();
  }

  // URL-decode the slug (page.tsx itself decodeURIComponent's `name`, so the
  // allowlist comparison must do the same to stay consistent).
  let slug: string;
  try {
    slug = decodeURIComponent(match[1]);
  } catch {
    // Malformed URI sequence — that's a 404 on its own.
    return NextResponse.rewrite(request.nextUrl, { status: 404 });
  }

  if (ALLOWLIST.has(slug)) {
    return NextResponse.next();
  }

  // Unknown or private slug: rewrite back to the same URL but with HTTP 404.
  // The route still renders notFound() → segment not-found.tsx body, so the
  // visible page stays correct; only the status code changes.
  return NextResponse.rewrite(request.nextUrl, { status: 404 });
}
